version: "3"
services:
  server:
    image: jetbrains/teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
  teamcity-agent:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=regular_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
